gchar* introspection_xml = "<?xml version='1.0' encoding='UTF-8'?>"
"<!DOCTYPE node PUBLIC '-//freedesktop//DTD D-BUS Object Introspection 1.0//EN'"
"	'http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd'>"
"<node name='/org/gitorious/gboard'>"
"	<interface name='org.gitorious.gboard'>"
"		<method name='Open'>"
"			<arg name='Recognizer' type='b' direction='in' />"
"		</method>"
"		<method name='Close'>"
"			<arg name='Force' type='b' direction='in' />"
"			<arg name='Closed' type='b' direction='out' />"
"		</method>"
"		<signal name='Finish'>"
"			<arg name='Text' type='s' />"
"		</signal>"
"		<signal name='Change'>"
"			<arg name='Text' type='s' />"
"		</signal>"
"		<signal name='Cancel' />"
"		<property name='Visible' type='b' access='read' />"
"		<property name='Recognizer' type='b' access='read' />"
"	</interface>"
"</node>";
